# Generated by Django 3.2.12 on 2022-03-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('authors', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='regions',
            field=models.ManyToManyField(blank=True, to='regions.Region'),
        ),
    ]
